baseurl                  = "https://rubyist.org/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "rubyist"
theme                    = "sam"
pygmentsStyle            = "monokai"
pygmentsCodefences       = true
googleAnalytics          = "UA-49505169-3"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    homepage             = "main"                           # What to call the home page link
    footerText           = "rubyist"

# Metadata for Open Graph and Twitter
    description          = "rubyist.org"
    images               = ["ruby.jpeg"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "rubyist"

[[params.mainMenu]]
    text = "rubyist"

[imaging]
    quality = 75